version: '3.9'

services:
  gatsby:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/openousd
      - /openousd/node_modules #https://justlike.medium.com/how-to-avoid-overriding-node-modules-in-docker-for-local-development-20f412444589
    stdin_open: true
    tty: true
    command: "gatsby develop -H 0.0.0.0 -p 8000"
