export const DESCRIPTION = "description"
export const VALUE = "value"
export const STAFF = "staff"
export const OVER_BY = "over_by"
export const UNDER_BY = "under_by"

export const CHANGE = "change_from_previous_year"
export const SPENDING = "spending"
export const BUDGET = "budget"
export const BALANCE = "budget_balance"
export const STAFF_FTE = "eoy_total_fte"
export const STAFF_POSITIONS = "eoy_total_positions"
